### ISSUE TITLE
skull_texture value is not a valid custom data

### ISSUE THREAD

**Issue by Bufhimat** [DerFrZocker/Custom-Ore-Generator#1]
I'm getting an error when adding the skull_texture. However you can /give yourself this head. The texture is hosted on education.minecraft.net, not textures.minecraft.net.

> oregen set customdata world copper_ore skull_texture eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHBzOi8vZWR1Y2F0aW9uLm1pbmVjcmFmdC5uZXQvd3AtY29udGVudC91cGxvYWRzL2NvcHBlcl9vcmUucG5nIn19fQ==
[23:39:37 INFO]: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHBzOi8vZWR1Y2F0aW9uLm1pbmVjcmFmdC5uZXQvd3AtY29udGVudC91cGxvYWRzL2NvcHBlcl9vcmUucG5nIn19fQ==' is not a valid custom data!

/give @p player_head{SkullOwner:{Id:"314d6164-6520-6279-2052-756e61696963",Name:"Copper Ore",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHBzOi8vZWR1Y2F0aW9uLm1pbmVjcmFmdC5uZXQvd3AtY29udGVudC91cGxvYWRzL2NvcHBlcl9vcmUucG5nIn19fQ=="}]}}}

**Comment by DerFrZocker** [comment]
Fixed in newest version.
