### ISSUE TITLE
[Question/Suggestion] How it configure spawn chance per chunk 

### ISSUE THREAD

**Issue by Chandr0** [DerFrZocker/Custom-Ore-Generator#24]
Pls tell me how to configure chance of spawning an ore per chunk like 70% or 30%. If it isn't possible, please add such feature, it will be much easier to configure

**Comment by DerFrZocker** [comment]
You can set the VEINS_PER_CHUNK setting to 0.7 for a 70% chance or 0.3 for a 30% chance.
